# This example is specific for Debian, run the following commands before starting the compose:
# modprobe binder_linux devices=binder1,binder2,binder3,binder4,binder5,binder6
# chmod 666 /dev/binder*
#
# You may find the Redroid deploy instructions for other distros here: https://github.com/remote-android/redroid-doc/tree/master/deploy
#
# The ./init.d folder should contain the "setup.sh" and "reset.sh" scripts

services:
  bh-demo-android:
    privileged: true
    volumes:
      - /dev/binder1:/dev/binder
      - /dev/binder2:/dev/hwbinder
      - /dev/binder3:/dev/vndbinder
    ports:
      - 5555:5555 # No need to expose this, but it's useful for debugging purposes
    container_name: android-bh-demo-avd
    image: redroid/redroid:14.0.0-latest
  bh-demo-droidground:
    image: ghcr.io/secforce/droidground:v0.2.8
    container_name: android-bh-demo-droidground
    restart: unless-stopped
    ports:
      - 4242:4242
    volumes:
      - ./init.d:/init.d
    environment:
      - DROIDGROUND_APP_PACKAGE_NAME=com.blackhat.multistep
      - DROIDGROUND_ADB_HOST=localhost
      - DROIDGROUND_ADB_PORT=5037
      - DROIDGROUND_DEVICE_TYPE=network
      - DROIDGROUND_DEVICE_HOST=android-bh-demo-avd
      - DROIDGROUND_DEVICE_PORT=5555
      - DROIDGROUND_INIT_SCRIPTS_FOLDER=/init.d
      - DROIDGROUND_HOST=0.0.0.0
      - DROIDGROUND_PORT=4242
      - DROIDGROUND_SHUTDOWN_DISABLED=true
      - DROIDGROUND_REBOOT_DISABLED=true
      - DROIDGROUND_BUG_REPORT_DISABLED=true
      - DROIDGROUND_APP_MANAGER_DISABLED=false
      - DROIDGROUND_FRIDA_DISABLED=true
      - DROIDGROUND_START_ACTIVITY_DISABLED=true
      - DROIDGROUND_START_RECEIVER_DISABLED=true
      - DROIDGROUND_START_SERVICE_DISABLED=true
      - DROIDGROUND_TERMINAL_DISABLED=true
      - DROIDGROUND_EXPLOIT_APP_DURATION=20